### PR TITLE
styling: centering gauge + added background to card

### PR DESCRIPTION
**Pull request by kdw2060**
Added a css property as to center the gauge on the card and css code to give the card a background and box-shadow just like the standard cards.

I thought users would expect it to look and feel more like the standard cards, but it's ok to dismiss this request if you don't agree, it's your work after all.

### CODE REVIEW

**Comment by bmorgan99** [comment]
FWIW, I would like this too.

**Comment by hpcodecraft** [comment]
This would be great

**Comment by iantrich** [comment]
Merging as it looks to still be valid and @helto4real hasn't been around for awhile it appears.

**Comment by helto4real** [comment]
Thanks @iantrich and sorry totally missed this PR , think I need to filter those spam from GitHub haha sorry @kdw2060 thanks for your contribution!

**Pull request merged**
